In [228]:
import cv2
import numpy as np
import os

In [229]:
class_names = os.listdir('Train')
class_names

['Bikes', 'Horses']

In [230]:
images = [] #Get path to all images and save them in a list
labels = [] # labels of corresponding images
class_id = 0

for i in class_names:
    dir=os.path.join('train',i)
    x = [os.path.join(dir, f) for f in os.listdir(dir)]
    images+= x
    labels+=[class_id]*len(x)
    class_id+=1

In [231]:
images

['train\\Bikes\\0001.jpg',
 'train\\Bikes\\0002.jpg',
 'train\\Bikes\\0003.jpg',
 'train\\Bikes\\0004.jpg',
 'train\\Bikes\\0005.jpg',
 'train\\Bikes\\0006.jpg',
 'train\\Bikes\\0007.jpg',
 'train\\Bikes\\0008.jpg',
 'train\\Bikes\\0009.jpg',
 'train\\Bikes\\0010.jpg',
 'train\\Bikes\\0011.jpg',
 'train\\Bikes\\0012.jpg',
 'train\\Bikes\\0013.jpg',
 'train\\Bikes\\0014.jpg',
 'train\\Bikes\\0015.jpg',
 'train\\Bikes\\0016.jpg',
 'train\\Bikes\\0017.jpg',
 'train\\Bikes\\0018.jpg',
 'train\\Bikes\\0019.jpg',
 'train\\Bikes\\0020.jpg',
 'train\\Bikes\\0021.jpg',
 'train\\Bikes\\0022.jpg',
 'train\\Bikes\\0023.jpg',
 'train\\Bikes\\0024.jpg',
 'train\\Bikes\\0025.jpg',
 'train\\Bikes\\0026.jpg',
 'train\\Bikes\\0027.jpg',
 'train\\Bikes\\0028.jpg',
 'train\\Bikes\\0029.jpg',
 'train\\Bikes\\0030.jpg',
 'train\\Bikes\\0031.jpg',
 'train\\Bikes\\0032.jpg',
 'train\\Bikes\\0033.jpg',
 'train\\Bikes\\0034.jpg',
 'train\\Bikes\\0035.jpg',
 'train\\Bikes\\0036.jpg',
 'train\\Bikes\\0037.jpg',
 

In [232]:
labels

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

Randomly Suffling The Dataset and Doing Train-Test Split

In [233]:
import random
D = []
for i in range(len(images)):
    D.append([images[i],labels[i]])

dataset = D
random.shuffle(dataset)
train = dataset[:155]
test = dataset[155:]

x_train, y_train = zip(*train)
x_test, y_test = zip(*test)

Detecting Keypoints and Corresponding Descriptors

In [234]:
sift = cv2.SIFT_create()

In [235]:
imgwise_des_list = []
des_list = []
for t in x_train:
    im = cv2.imread(t)
    kpts, des = sift.detectAndCompute(im, None)
    imgwise_des_list.append((t, des)) 
    for i in des:
        des_list.append(i)
des_list = np.array(des_list) 

In [254]:
imgwise_des_list

[('train\\Horses\\horse52.jpg',
  array([[  5.,   3.,   0., ...,   0.,   1.,  34.],
         [ 14.,   3.,   0., ...,   0.,   0.,   0.],
         [  0.,   0.,   0., ...,   6.,   0.,   2.],
         ...,
         [ 14.,  13., 119., ...,   0.,   0.,   2.],
         [ 79.,   5.,   1., ...,   0.,   0.,   0.],
         [  0.,   0.,   0., ...,  50.,   5.,  18.]], dtype=float32)),
 ('train\\Bikes\\0047.jpg',
  array([[ 0.,  2.,  4., ...,  0.,  1.,  1.],
         [ 1.,  3., 20., ...,  1.,  2.,  5.],
         [ 0.,  0.,  0., ...,  0.,  0.,  1.],
         ...,
         [72., 17.,  0., ...,  0.,  0.,  4.],
         [70., 18.,  1., ...,  1.,  1.,  3.],
         [55., 16.,  3., ...,  2.,  1.,  2.]], dtype=float32)),
 ('train\\Horses\\horse3 .jpg',
  array([[101.,  27.,  19., ...,   5.,   0.,   1.],
         [  0.,   0.,   0., ...,   0.,  11.,  87.],
         [  6.,   2.,   1., ...,  25.,   2.,   1.],
         ...,
         [  0.,   6.,  35., ...,   0.,   0.,   0.],
         [ 20., 110.,  23., ...,  

In [252]:
im.shape

(307, 500, 3)

In [236]:
des_list

array([[  6.,  55., 131., ...,   2.,   2.,   1.],
       [  2.,  31.,  43., ...,   0.,   0.,   9.],
       [  0.,   5.,  87., ...,   1.,   0.,   1.],
       ...,
       [ 58.,  46.,   0., ...,   0.,   0.,  11.],
       [ 60.,  28.,   5., ...,   0.,   0.,  11.],
       [ 48.,  13.,   3., ...,   1.,   2.,   7.]], dtype=float32)

Clustering of Descriptors

In [237]:
from scipy.cluster.vq import kmeans, vq
k = 200  
voc, variance = kmeans(des_list, k, 1) 


In [238]:
voc.shape

(200, 128)

In [239]:
variance

271.37494

Computing Histograms

In [240]:
histograms = np.zeros((len(x_train), k), "float32")
histograms.shape

(155, 200)

In [241]:
histograms

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [242]:
for i in range(len(x_train)):
    words, distance = vq(imgwise_des_list[i][1],voc)
    for w in words:
        histograms[i][w] += 1

In [243]:
words.shape

(785,)

In [244]:
imgwise_des_list[len(x_train)-1][1].shape

(785, 128)

In [245]:
histograms.shape

(155, 200)

In [246]:
histograms #each row represents histogram of one image

array([[ 4.,  6.,  0., ...,  2.,  4.,  0.],
       [ 4.,  2.,  0., ...,  8.,  4.,  6.],
       [ 4.,  4.,  2., ...,  7.,  3.,  3.],
       ...,
       [43.,  7.,  7., ...,  7., 10.,  4.],
       [ 2.,  4.,  2., ...,  3.,  4.,  1.],
       [ 1.,  3.,  2., ...,  4.,  3.,  3.]], dtype=float32)

Scaling the words
Standardize features by removing the mean and scaling to unit variance
In a way normalization

In [247]:
from sklearn.preprocessing import StandardScaler
stdSlr = StandardScaler().fit(histograms)
histograms = stdSlr.transform(histograms)

Train an algorithm to discriminate vectors corresponding to positive and negative training images
Train the Linear SVM

In [248]:
from sklearn.svm import LinearSVC
y_train = np.asarray(y_train, dtype=np.float32)
clf = LinearSVC(max_iter=80000)  #Default of 100 is not converging
clf.fit(histograms,y_train)

LinearSVC(max_iter=80000)

TESTING

In [249]:
imgwise_des_list = []
des_list = []
for t in x_test:
    im = cv2.imread(t)
    kpts, des = sift.detectAndCompute(im, None)
    imgwise_des_list.append((t, des)) 
    for i in des:
        des_list.append(i)
des_list = np.array(des_list) 

histograms = np.zeros((len(x_test), k), "float32")

for i in range(len(x_test)):
    words, distance = vq(imgwise_des_list[i][1],voc)
    for w in words:
        histograms[i][w] += 1
        
stdSlr = StandardScaler().fit(histograms)
histograms = stdSlr.transform(histograms)


In [250]:
y_test = np.asarray(y_test, dtype=np.float32)
predictions=clf.predict(histograms)
def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

print(get_accuracy(predictions,y_test))

[1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.] [1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
0.9583333333333334
